# Generated by Django 4.1.6 on 2023-02-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
